Vagrant.configure("2") do |config|
    config.vm.define "machine-name" do |s|
        s.vm.box = "bento/ubuntu-20.04"

        s.vm.provision :shell, inline: "sudo apt update && sudo apt install ansible -y"
        s.vm.synced_folder "./ansible", "/ansible", mount_options: ["dmode=775,fmode=664"]
    end
end
