
name: "Prepare Python environment"
description: "Prepare Python environment"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: extractions/setup-just@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Install pipenv
      run: |
        pip install pipenv
      shell: bash
    - name: Cache Dependencies
      uses: actions/cache@v2
      id: cache-dependencies
      with:
        path: ./.venv
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv
    - name: Install requirements
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        pipenv install --dev --verbose
      shell: bash
      env:
        PIPENV_VENV_IN_PROJECT: enabled
